#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_fd1 = \
Coefficients.f \
CustomDouble.f \
Geometry.f \
Properties.f \
Results.f \
Solver.f \
Testing.f \
main.f 

OBJS_fd1 = \
Coefficients.o \
CustomDouble.o \
Geometry.o \
Properties.o \
Results.o \
Solver.o \
Testing.o \
main.o 

SRC_DIR_fd1 = src/
OBJS_DIR = obj/Release/src/
EXE_DIR = bin/Release/

EXE = MTFDTrab2.exe
FC = gfortran.exe
LD = gfortran.exe
IDIR = 
CFLAGS = -fimplicit-none -ffree-line-length-none -ffixed-line-length-none -ffixed-form -Wall -march=corei7 -ffast-math -fexpensive-optimizations -O3 -fimplicit-none -ffree-line-length-none -ffixed-line-length-none -fdefault-integer-8 -fdefault-double-8 -fdefault-real-8 -ffixed-form  -J$(OBJS_DIR) $(IDIR)
LFLAGS = -s 
LIBS = 

VPATH = $(SRC_DIR_fd1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_fd1))

all : $(EXE)

$(EXE) : $(OBJS_fd1)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_fd1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_fd1)$(@:.o=.f) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# File dependencies
Coefficients.o: \
    Coefficients.f \
    Properties.o
CustomDouble.o: \
    CustomDouble.f
Geometry.o: \
    Geometry.f
Properties.o: \
    Properties.f
Results.o: \
    Results.f \
    Properties.o
Solver.o: \
    Solver.f \
    Coefficients.o \
    Properties.o \
    Results.o
Testing.o: \
    Testing.f \
    Coefficients.o \
    CustomDouble.o \
    Geometry.o \
    Results.o \
    Solver.o
main.o: \
    main.f \
    Coefficients.o \
    Geometry.o \
    Properties.o \
    Results.o \
    Solver.o

